[xtBed]
  patches-src = "./patches"

[xtBed.meta]
  author = "MyAuthor"

[basic]
  target = "src/calculator.c"
  patches = ["calculator/sum.patch", "calculator/subtract.patch", "calculator/multiply.patch"]

[basic.validator]
  exec = "gcc calculator.c -o calculator.o"

[complex]
  target = "src/complex.c"

[[complex.patches]]
  name = "prepare-patch"
  paths = ["../ext-patch/prepare-complex"]

[[complex.patches]]
  name = "permute-options"
  type = "parallel"
  paths = ["complex/impl/opt1", "complex/impl/opt1"]
  validator = "gcc basic.c -o basic.o"
